ANT	= env LC_ALL=ja_JP.UTF-8 ant

all:
	$(ANT) all

clean:
	$(ANT) clean
	
treetest:
	$(ANT) treetest
    
foresttest:
	$(ANT) foresttest

semilatticetest:
	$(ANT) semilatticetest

install:
	$(ANT) install

doc:
	$(ANT) doc

zip:
	$(ANT) zip
